version: '3.1'

services:
    nginx:
        image: nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - ./nginx.conf/setting/test1.conf:/etc/nginx/conf.d/test1.conf:ro
            - ./nginx.conf/setting/test2.conf:/etc/nginx/conf.d/test2.conf:ro
            
    
    wordpress_test1:
        image: wordpress
        restart: always
        ports:
            - 8081:80
        environment:
            WORDPRESS_DB_HOST: db_test1
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - wordpress_test1:/var/www/html

    db_test1:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db_test1:/var/lib/mysql

    wordpress_test2:
        image: wordpress
        restart: always
        ports:
            - 8082:80
        environment:
            WORDPRESS_DB_HOST: db_test2
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - wordpress_test2:/var/www/html

    db_test2:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db_test2:/var/lib/mysql

volumes:
    wordpress_test1:
    wordpress_test2:
    db_test1:
    db_test2:
